init:
  home: "~/.mantrachain"
accounts:
  - name: validator
    coins:
      - 1500000000000aum
    mnemonic:
      guard cream sadness conduct invite crumble clock pudding hole grit liar
      hotel maid produce squeeze return argue turtle know drive eight casino maze host
validator:
  name: validator
  staked: "500000000000aum"
genesis:
  chain_id: "localnet"
  app_state:
    liquidity:
    liquidfarming:
      params:
        rewards_auction_duration: "120s"
        liquid_farms:
          - pool_id: "1"
            min_farm_amount: "1"
            min_bid_amount: "1"
            fee_rate: "0.000000000000000000"