version: 1
init:
  home: "$HOME/.mantrachain"
build:
  ldflags:
    - -X github.com/MANTRA-Finance/mantrachain/x/liquidfarming/keeper.enableAdvanceAuction=true
  proto:
    path: proto
accounts:
  - name: alice # cre1zaavvzxez0elundtn32qnk9lkm8kmcszxclz6p
    coins:
      - 1000000000000000uaum
      - 1000000000000000uusd
    mnemonic:
      guard cream sadness conduct invite crumble clock pudding hole grit liar
      hotel maid produce squeeze return argue turtle know drive eight casino maze host
  - name: bob # cre1mzgucqnfr2l8cj5apvdpllhzt4zeuh2c5l33n3
    coins:
      - 1000000000000000uaum
      - 1000000000000000uusd
    mnemonic:
      friend excite rough reopen cover wheel spoon convince island path clean
      monkey play snow number walnut pull lock shoot hurry dream divide concert discover
  - name: steve # cre185fflsvwrz0cx46w6qada7mdy92m6kx4vg42xf
    coins:
      - 1000000000000000uaum
      - 1000000000000000uusd
    mnemonic:
      fuel obscure melt april direct second usual hair leave hobby beef bacon
      solid drum used law mercy worry fat super must ritual bring faculty
validator:
  name: alice
  staked: 100000000uaum
faucet:
  name: bob
  coins:
    - 10000000uaum
  host: 0.0.0.0:4500
genesis:
  chain_id: "localnet"
  app_state:
    crisis:
      constant_fee:
        denom: "uaum"
    mint:
      params:
        mint_denom: "uaum"
    staking:
      params:
        bond_denom: "uaum"
    gov:
      deposit_params:
        min_deposit:
          - amount: "1"
            denom: "uaum"
      voting_params:
        voting_period: "20s"
    budget:
      params:
        budgets:
          - name: "incentivize-marketmaker-20201Q-20301Q"
            rate: "0.300000000000000000"
            source_address: "mantrachain17xpfvakm2amg962yls6f84z3kell8c5l53s97s" # fee collector account
            destination_address: "mantrachain1ddn66jv0sjpmck0ptegmhmqtn35qsg2vxyk2hn9sqf4qxtzqz3sq3qhhde"
            start_time: "2020-03-01T00:00:00Z"
            end_time: "2030-03-01T00:00:00Z"
    liquidity:
      params:
        pair_creation_fee:
          - amount: "100000"
            denom: "uaum"
        pool_creation_fee:
          - amount: "100000"
            denom: "uaum"
   