version: 1
# GENESIS ACCOUNTS
accounts:
- name: validator
  coins: ["10000000000000000uaum"]
  mnemonic: clever spin draw twelve document tornado panther crisp picture feel remind want basket uncle stove aisle hamster velvet dry protect buyer fiber choice answer
- name: admin
  coins: ["10000000000000000uaum"]
  address: mantra1axznhnm82lah8qqvp9hxdad49yx3s5dcj66qka
- name: recipient
  coins: ["10000000000000000uaum"]
  mnemonic: captain roast forget tree cliff common peasant unhappy reflect hole they essence trash paper slab carpet engine exist urge bulk kite trade rocket kid
# VALIDATORS
validators:
  - name: validator
    bonded: 100000000uaum
    # UPDATE app.toml
    app:
      pruning: "nothing"
      minimum-gas-prices: "0uaum"
    # UPDATE config.toml
    config:
      moniker: "mantra-dev-01"
      proxy_app: "tcp://0.0.0.0:26658"
    client:
      node: "tcp://0.0.0.0:26657"
# UPDATE GENESIS
genesis:
  app_state:
    staking:
      params:
        bond_denom: "uaum"
    crisis:
      constant_fee:
        denom: "uaum"
    gov:
      deposit_params:
        min_deposit:
          - "amount": "10000000"
            "denom": "uaum"
    mint:
      params:
        mint_denom: "uaum"
    lpfarm:
      params:
        private_plan_creation_fee: [{"amount": "1000000", "denom": "uaum"}]
    liquidity:
      params:
        pair_creation_fee: [{"amount": "1000000", "denom": "uaum"}]
        pool_creation_fee: [{"amount": "1000000", "denom": "uaum"}]
    bank:
      denom_metadata: [{"name":"aum","symbol":"AUM","description":"The native staking token of the Mantrachain.","denom_units":[{"denom":"uaum","exponent":0,"aliases":["microaum"]},{"denom":"maum","exponent":3,"aliases":["milliaum"]},{"denom":"aum","exponent":6}],"base":"uaum","display":"aum"}]
    guard:
      params:
        admin_account: "mantra1axznhnm82lah8qqvp9hxdad49yx3s5dcj66qka"
        account_privileges_token_collection_creator: "mantra1axznhnm82lah8qqvp9hxdad49yx3s5dcj66qka"
        account_privileges_token_collection_id: "account_privileges_guard_nft_collection"
# JS CLIENT
client:
  openapi:
    path: docs/static/openapi.yml
