// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: fractionnft/v1/tx.proto

package fractionnftv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_UpdateParams_FullMethodName   = "/fractionnft.v1.Msg/UpdateParams"
	Msg_MsgTokenizeNFT_FullMethodName = "/fractionnft.v1.Msg/MsgTokenizeNFT"
	Msg_MsgRemintNFT_FullMethodName   = "/fractionnft.v1.Msg/MsgRemintNFT"
	Msg_MsgMintNFT_FullMethodName     = "/fractionnft.v1.Msg/MsgMintNFT"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the Msg service.
type MsgClient interface {
	// UpdateParams defines a governance operation for updating the parameters.
	//
	// Since: cosmos-sdk 0.47
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	MsgTokenizeNFT(ctx context.Context, in *MsgTokenizeNFTParams, opts ...grpc.CallOption) (*MsgTokenizeNFTResponse, error)
	MsgRemintNFT(ctx context.Context, in *MsgRemintNFTParams, opts ...grpc.CallOption) (*MsgRemintNFTResponse, error)
	MsgMintNFT(ctx context.Context, in *MsgMintNFTParams, opts ...grpc.CallOption) (*MsgMintNFTResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MsgTokenizeNFT(ctx context.Context, in *MsgTokenizeNFTParams, opts ...grpc.CallOption) (*MsgTokenizeNFTResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgTokenizeNFTResponse)
	err := c.cc.Invoke(ctx, Msg_MsgTokenizeNFT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MsgRemintNFT(ctx context.Context, in *MsgRemintNFTParams, opts ...grpc.CallOption) (*MsgRemintNFTResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRemintNFTResponse)
	err := c.cc.Invoke(ctx, Msg_MsgRemintNFT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MsgMintNFT(ctx context.Context, in *MsgMintNFTParams, opts ...grpc.CallOption) (*MsgMintNFTResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgMintNFTResponse)
	err := c.cc.Invoke(ctx, Msg_MsgMintNFT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the Msg service.
type MsgServer interface {
	// UpdateParams defines a governance operation for updating the parameters.
	//
	// Since: cosmos-sdk 0.47
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	MsgTokenizeNFT(context.Context, *MsgTokenizeNFTParams) (*MsgTokenizeNFTResponse, error)
	MsgRemintNFT(context.Context, *MsgRemintNFTParams) (*MsgRemintNFTResponse, error)
	MsgMintNFT(context.Context, *MsgMintNFTParams) (*MsgMintNFTResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) MsgTokenizeNFT(context.Context, *MsgTokenizeNFTParams) (*MsgTokenizeNFTResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MsgTokenizeNFT not implemented")
}
func (UnimplementedMsgServer) MsgRemintNFT(context.Context, *MsgRemintNFTParams) (*MsgRemintNFTResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MsgRemintNFT not implemented")
}
func (UnimplementedMsgServer) MsgMintNFT(context.Context, *MsgMintNFTParams) (*MsgMintNFTResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MsgMintNFT not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call pancis, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MsgTokenizeNFT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTokenizeNFTParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MsgTokenizeNFT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_MsgTokenizeNFT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MsgTokenizeNFT(ctx, req.(*MsgTokenizeNFTParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MsgRemintNFT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemintNFTParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MsgRemintNFT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_MsgRemintNFT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MsgRemintNFT(ctx, req.(*MsgRemintNFTParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MsgMintNFT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMintNFTParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MsgMintNFT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_MsgMintNFT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MsgMintNFT(ctx, req.(*MsgMintNFTParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fractionnft.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "MsgTokenizeNFT",
			Handler:    _Msg_MsgTokenizeNFT_Handler,
		},
		{
			MethodName: "MsgRemintNFT",
			Handler:    _Msg_MsgRemintNFT_Handler,
		},
		{
			MethodName: "MsgMintNFT",
			Handler:    _Msg_MsgMintNFT_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fractionnft/v1/tx.proto",
}
