name: Build Mantrachaind
on:
  pull_request:
    branches:
      - main
      - release/**
  merge_group:
  push:
    branches:
      - main
      - release/**
permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
        # TODO: uncomment the following lines once wasm cross-compilation is supported
        # goos: [linux, windows, darwin]
        # goarch: [amd64, arm64]
        # exclude:
        #   - goarch: arm64
        #     goos: windows
    steps:
      - uses: actions/checkout@v4
      # - uses: DeterminateSystems/nix-installer-action@main
      # - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
      - name: Build
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make build
# Todo: add nix build with rocksdb
